version: "3"

services:
  my-web-db-1:
    image: avborovets/restful_api_example
    container_name: my-web-db-1
    ports:
      - 8081:8099
  my-web-db-2:
    image: avborovets/restful_api_example
    container_name: my-web-db-2
    ports:
      - 8082:8099
  my-web-db-3:
    image: avborovets/restful_api_example
    container_name: my-web-db-3
    ports:
      - 8083:8099

  envoy:
    build:
      context: ./envoy
    container_name: envoy
    ports:
      - 8080:10000
      - 9901:9901
    volumes:
      - ./envoy/logs/file.log:/tmp/admin_access.log
    depends_on:
      - my-web-db-1
      - my-web-db-2
      - my-web-db-3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - envoy

  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      restart: unless-stopped
      volumes:
        - ./grafana:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana
    # depends_on:
    #   - prometheus

volumes:
  grafana-data:
