global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
- job_name: envoy
  metrics_path: /stats/prometheus
  static_configs:
  - targets:
    - host.docker.internal:9901  # localhost:9901 does not work