---
# tasks file for prometheus
- debug:
    msg: "Deploy {{ env }}-{{ service_name }}"

- name: Create dir for datasources
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    mode: 0777

# - name: Create dir for plugins
#   file:
#     path: etc/grafana/provisioning/plugins
#     state: directory
#     mode: 0777

# - name: Create dir for notifiers
#   file:
#     path: etc/grafana/provisioning/notifiers
#     state: directory
#     mode: 0777

- name: Copy config.ini
  copy:
    src: config.ini
    dest: /etc/grafana/config.ini
    mode: 0777

- name: Copy datasource
  copy:
    src: prometheus_ds.yml
    dest: /etc/grafana/provisioning/datasources/prometheus_ds.yml
    mode: 0777

- name: Create directory for dashboard info
  file:
    path: /etc/grafana/provisioning/dashboards
    state: directory
    mode: 0777

- name: Copy dashboard yml
  copy:
    src: dashboard.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yml
    mode: 0777

- name: Create directory for dashboard-panels
  file:
    path: /var/lib/grafana/dashboards/kekule
    state: directory
    mode: 0777

- name: Copy dashboards json
  copy:
    src: my-panel.json
    dest: /var/lib/grafana/dashboards/kekule/my-panel.json
    mode: 0777

- name: Change owner
  ansible.builtin.shell: chown -R 472:0 /etc/grafana

- name: Restart a container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart: true
    user: 472
    volumes:
      - /etc/grafana:/etc/grafana
      - /var/lib/grafana:/var/lib/grafana
    env:
      GF_PATHS_CONFIG: "/etc/grafana/config.ini"
    ports:
      - 3000:3000

- name: Create a network
  community.docker.docker_network:
    name: my_super_network

- name: Create network between grafana-container and prometheus-container
  community.docker.docker_network:
    name: my_super_network
    connected:
      - grafana
      - prometheus
